### ISSUE TITLE
Image of sent messages disappears after a few days

### ISSUE THREAD

**Issue by CeciliaRavera** [cristianoag/microsoft-teams-apps-company-communicator#33]
When the message is sent, after a few days or weeks the image linked to the message disappears. The image was always added uploading a picture and not linking the public url. The image disappears both in the communicator chat and also in the sent messages preview in the author interface.
<img width="515" alt="rpboema" src="https://user-images.githubusercontent.com/44054900/182592672-79d509fc-67dd-4e4a-8ae8-8a4912611cb2.png">
Do you know why this happens?

Thanks

**Comment by CeciliaRavera** [comment]
Note: the ImageUploadBlobStorage setting is NOT enabled

**Comment by pgriziotti** [comment]
I can confirm the problem, the images do not load because even if the image upload functionality on the storage blob is not enabled the images are still loaded, and after 1 week they are no longer visible because it is the default expiration of the SAS token arrives.
The primary problem is that if ImageUploadBlobStorage is NOT present in the application configuration, the default is TRUE. So only if you set explicit ImageUploadBlobStorage to FALSE the image is disabled ...
I tried 4.45 and it doesn't have this problem, 4.51 and 5.13 have this problem. I think at some point the default was changed ...

**Comment by danilonogueira** [comment]
Any perspective of resolve this problem?

**Comment by pgriziotti** [comment]
adding the config value ImageUploadBlobStorage to false, fix the issue for new messages.

**Comment by danilonogueira** [comment]
This way?
![image](https://user-images.githubusercontent.com/4694421/192803288-905629ae-f71b-40b0-9f49-cd40a2f117ae.png)
![image](https://user-images.githubusercontent.com/4694421/192803341-dfdfba38-5261-477e-8bd9-c4d528a02662.png)

**Comment by danilonogueira** [comment]
but with ImageUploadBlobStorage "false", images has limit of 30kb to upload. If I set to TRUE resolve?

**Comment by andersonafp** [comment]
It seems this problem happens on Teams Desktop and Teams Web, but not on Teams Mobile for some reason. 
As long as I couldn't find a solution for upload big images I am uploading the image on a free image host and coping the URL into the CC app.

Step by step:
https://app.tango.us/app/workflow/Upload-images-that-does-not-disaper-into-CC-b38d0ddeeb424801875523e8ce432177

**Comment by mustafafarooq** [comment]
Looking for a solution on this urgently , experiencing the same

**Comment by cristianoag** [comment]
This happens because there is a default expiration value for the images you upload to the blob storage. You can change the ImageUploadBlobStorageSasDurationHours value on the configuration. The default value is 168 hours (which is one week). More info available at https://tech-peanuts.com/2022/01/24/company-communicator-upload-images-to-azure-blob-storage/
